# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SWAV_BIO
                                 A QGIS plugin
 This plugin allows to obtain the biomass in rocky beach
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-23
        copyright            : (C) 2020 by Projeto SWAV
        email                : liaduarte@fc.up.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SWAV_BIO class from file SWAV_BIO.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .swav_bio import SWAV_BIO
    return SWAV_BIO(iface)
